version: '3.6'
services:
  server:
    build: 
      context: .
      dockerfile: nodejs_Dockerfile
    env_file: properties.env
    depends_on: 
      - db
    ports:
      - '8079:8079'
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
    command: node src/server.js
    logging:
      driver: 'json-file'
      options:
        max-file: '3'
        max-size: 1m
    restart: always
  db:
    build: 
      context: .
      dockerfile: mariadb_Dockerfile
    env_file: properties.env
    volumes:
      - ./init_files/initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_datas:/var/lib/mysql/
    logging:
      driver: 'json-file'
      options:
        max-file: '3'
        max-size: 1m
    restart: always
