version: '3.6'
services:
  server:
    build: 
      context: .
      dockerfile: nodejs_Dockerfile
    env_file: properties.env
    depends_on: 
      - db
    ports:
      - '8077:8079'
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
    command: node src/server.js
  db:
    build: 
      context: .
      dockerfile: mariadb_Dockerfile
    env_file: properties.env
    volumes:
      - ./init_files/initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_datas:/var/lib/mysql/
